In [5]:
#########################################

In [9]:
from glob import glob
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
import tensorflow as tf
import os
from sklearn.model_selection import train_test_split

In [10]:
import tensorflow_addons as tfa

In [103]:
data_list = glob('/home/gangmin_data/capstone_data/training/*/*.jpg')
data_list2 = glob('/home/gangmin_data/capstone_data/training/1/*.JPG')

In [105]:
data_list = data_list + data_list2

In [106]:
test_data = glob('/home/gangmin_data/capstone_data/test/*/*.jpg')

In [107]:
print(len(data_list))
print(len(test_data))

2026
578


In [108]:
train, valid = train_test_split(data_list, test_size = 0.2,)

In [109]:
train_path = train
valid_path = valid
test_path = test_data

In [110]:
def get_label_from_path(path):
    list_label = []
    for i in range(len(path)):
        list_label.append(int(path[i].split('/')[-2]))
    return list_label

In [111]:
IMG_SIZE = 160 # 모든 이미지는 160x160으로 크기가 조정됩니다

def format_example(path):
    image = np.array(Image.open(path))
    image = tf.cast(image, tf.float32)k
    image = (image/127.5) - 1
    if image.ndim != (3 or 4):
        print(path, 'ndim =', image.ndim)
        os.remove(path)
    image = tf.image.resize(image, (IMG_SIZE, IMG_SIZE))
    return image


SyntaxError: invalid syntax (<ipython-input-111-85e6297ef6d9>, line 5)

In [112]:
batch_size = 32

batch_per_epoch =  len(data_list) // batch_size 

label = get_label_from_path(train_path)

val_label = get_label_from_path(valid_path)

test_label = get_label_from_path(test_path)


In [113]:
print(label)
print(len(label))

[2, 0, 2, 2, 2, 0, 2, 2, 1, 2, 0, 0, 1, 0, 2, 1, 0, 2, 0, 0, 0, 0, 1, 2, 2, 2, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 0, 1, 0, 2, 0, 1, 1, 0, 0, 0, 2, 1, 2, 2, 1, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 1, 1, 0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 1, 0, 1, 0, 2, 1, 2, 1, 2, 2, 0, 2, 0, 2, 2, 2, 0, 1, 2, 2, 0, 2, 2, 0, 0, 2, 2, 0, 2, 1, 0, 0, 1, 0, 0, 2, 0, 1, 0, 0, 2, 2, 0, 2, 2, 2, 1, 2, 2, 2, 1, 2, 0, 0, 1, 2, 0, 1, 0, 2, 0, 1, 2, 2, 2, 1, 1, 0, 2, 2, 1, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 2, 0, 0, 2, 2, 2, 2, 0, 2, 0, 0, 2, 2, 1, 0, 1, 1, 2, 2, 2, 2, 2, 0, 0, 2, 0, 0, 1, 2, 0, 0, 0, 2, 2, 0, 2, 0, 2, 1, 2, 1, 2, 1, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 1, 1, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 2, 1, 1, 0, 1, 2, 1, 1, 2, 2, 2, 0, 0, 2, 0, 2, 0, 0, 0, 1, 1, 0, 2, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 2, 1, 2, 2, 0, 1, 0, 0, 2, 2, 2, 0, 2, 2, 2, 0, 0, 0, 2, 0, 1, 2, 0, 2, 1, 2, 1, 0, 2, 1, 2, 2, 2, 2, 1, 0, 2, 0, 0, 2, 2, 0, 0, 1, 0, 2, 0, 0, 2, 1, 0, 2, 2, 2, 1, 0, 1, 1, 0, 2, 2, 0, 0, 2, 0, 1, 2, 0, 2, 2, 0, 2, 0, 2, 

In [114]:
print(test_label)
print(len(test_label))
print(test_label.count(1))

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [115]:
batch_size = 32
data_height = 160
data_width = 160
channel_n = 3

def make_Batch_image(data_list):
    batch_image = np.zeros((len(data_list), data_height, data_width,channel_n))
    for n in range(len(data_list)):
        path = data_list[n]
        image = format_example(path)
        if image.shape != (160,160,3):
            os.remove(path)
        else:
            batch_image[n,:,:,:] = image
    return batch_image

In [116]:
train_image = make_Batch_image(train_path)
test_image = make_Batch_image(test_data)
valid_image = make_Batch_image(valid_path)

In [117]:
print(train_image.shape)

(1620, 160, 160, 3)


In [118]:
def make_dataset(image, label):
    image = tf.cast(image, dtype = 'float32')
    label = tf.cast(label, dtype = 'uint8')
    ds = tf.data.Dataset.from_tensor_slices( (image, label)).shuffle(20).batch(32)
    return ds

In [119]:
train_ds = make_dataset(train_image, label)
test_ds = make_dataset(test_image, test_label)
valid_ds = make_dataset(valid_image, val_label)

In [120]:
train_ds
for image_batch, label_batch in train_ds.take(1):
    print(image_batch.shape)
    print(label_batch.shape)

(32, 160, 160, 3)
(32,)


In [121]:
IMG_SIZE = 160

def augment(image, label):
   # Random crop back to the original size
    image = tf.image.random_flip_up_down(image)
    image = tf.image.random_flip_left_right(image)
    image = tf.image.adjust_saturation(image,3)
    image = tf.image.random_brightness(image, max_delta = 0.4) # Random brightness
    return image, label

In [122]:
train_ds = (train_ds.shuffle(32).map(augment, num_parallel_calls = tf.data.experimental.AUTOTUNE).prefetch(tf.data.experimental.AUTOTUNE))

In [123]:
for img, label in train_ds.take(1):
    print(img)
    print(label)

tf.Tensor(
[[[[ 6.80160940e-01  5.15455067e-01  3.74278605e-01]
   [ 7.04239428e-01  5.39533556e-01  3.51298273e-01]
   [ 7.11925685e-01  5.47219813e-01  3.56631368e-01]
   ...
   [ 8.00553024e-01  5.88788331e-01  3.77023637e-01]
   [ 7.42670715e-01  5.23846090e-01  3.12081426e-01]
   [ 7.50749409e-01  5.15455306e-01  3.03690612e-01]]

  [[ 7.18356729e-01  5.39533854e-01  3.58357072e-01]
   [ 7.21729457e-01  5.42906582e-01  3.61729801e-01]
   [ 7.12709904e-01  5.33887029e-01  3.05651426e-01]
   ...
   [ 7.60161042e-01  5.48396349e-01  3.36631626e-01]
   [ 7.41258681e-01  5.05964577e-01  2.94199854e-01]
   [ 7.23298669e-01  4.88004565e-01  2.76239902e-01]]

  [[ 7.30749190e-01  5.18984497e-01  3.54278624e-01]
   [ 7.12709963e-01  5.00945270e-01  3.19768846e-01]
   [ 7.13494241e-01  5.01729548e-01  2.89964825e-01]
   ...
   [ 7.46827602e-01  5.11533499e-01  2.99768806e-01]
   [ 7.38984466e-01  5.03690362e-01  2.91925669e-01]
   [ 6.96239531e-01  4.60945427e-01  2.49180734e-01]]

  ...

 

In [133]:
IMG_SHAPE = (IMG_SIZE, IMG_SIZE, 3)
inception_model = tf.keras.applications.MobileNet(include_top = False, weights = 'imagenet', input_shape =(IMG_SHAPE))
fine_inception = tf.keras.applications.MobileNet(include_top = False, weights = 'imagenet', input_shape =(IMG_SHAPE))

In [134]:
inception_model.summary()

Model: "mobilenet_1.00_160"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_11 (InputLayer)        [(None, 160, 160, 3)]     0         
_________________________________________________________________
conv1 (Conv2D)               (None, 80, 80, 32)        864       
_________________________________________________________________
conv1_bn (BatchNormalization (None, 80, 80, 32)        128       
_________________________________________________________________
conv1_relu (ReLU)            (None, 80, 80, 32)        0         
_________________________________________________________________
conv_dw_1 (DepthwiseConv2D)  (None, 80, 80, 32)        288       
_________________________________________________________________
conv_dw_1_bn (BatchNormaliza (None, 80, 80, 32)        128       
_________________________________________________________________
conv_dw_1_relu (ReLU)        (None, 80, 80, 32) 

In [142]:
triplet_model = tf.keras.Sequential([
    inception_model,
    tf.keras.layers.GlobalAveragePooling2D(),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(1024),
    tf.keras.layers.Lambda(lambda x: tf.math.l2_normalize(x, axis=1)), # L2 normalize embeddings
])

In [143]:
triplet_model.compile(loss = tfa.losses.TripletSemiHardLoss(),
             optimizer = tf.keras.optimizers.Adam(learning_rate= 0.001),)

In [144]:
checkpoint_path = '/home/gangmin_data/capstone_data/checkpoint'
modelcheck = tf.keras.callbacks.ModelCheckpoint(filepath= checkpoint_path ,monitor= 'val_loss', save_best_only= True, mode = 'min', save_freq= 'epoch' )
callback = tf.keras.callbacks.EarlyStopping(monitor= 'val_loss', patience= 3)
triplet_model.fit(
    train_ds,
    validation_data = valid_ds,
    callbacks= [callback,modelcheck],
    epochs=100)

triplet_model = tf.keras.models.load_model(checkpoint_path)
triplet_model.evaluate(valid_ds, batch_size=128, verbose=1)

Epoch 1/100
51/51 [==============================] - 31s 567ms/step - loss: 0.3599 - val_loss: 0.5339
INFO:tensorflow:Assets written to: /home/gangmin_data/capstone_data/checkpoint/assets
Epoch 2/100
51/51 [==============================] - 29s 566ms/step - loss: 0.3872 - val_loss: 0.4363
INFO:tensorflow:Assets written to: /home/gangmin_data/capstone_data/checkpoint/assets
Epoch 3/100
51/51 [==============================] - 29s 558ms/step - loss: 0.3239 - val_loss: 0.5143
Epoch 4/100
51/51 [==============================] - 29s 555ms/step - loss: 0.2938 - val_loss: 0.5506
Epoch 5/100
13/13 [==============================] - 2s 96ms/step - loss: 0.5166


0.5165900588035583

In [145]:
triplet_model = tf.keras.models.load_model(checkpoint_path)
triplet_model.evaluate(valid_ds, batch_size=128, verbose=1)

13/13 [==============================] - 2s 95ms/step - loss: 0.5061


0.5060884356498718

In [146]:
triplet_model.trainble = False

In [147]:
!mkdir -p saved_model


triplet_model_result = tf.keras.Sequential([
    triplet_model,
    tf.keras.layers.Dense(128, activation = 'relu'),
    tf.keras.layers.Dense(64, activation = 'relu'),
    tf.keras.layers.Dense(3)
]) 
checkpoint_path2 = '/home/gangmin_data/capstone_data/checkpoint2'
modelcheck2 = tf.keras.callbacks.ModelCheckpoint(filepath= checkpoint_path2 ,monitor= 'val_loss', save_best_only= True, mode = 'min', save_freq= 'epoch' )

triplet_model_result.compile(loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits= True),
             optimizer = tf.keras.optimizers.Adam(learning_rate= 0.0001),
             metrics = ['accuracy'])

triplet_model_result.fit(train_ds, validation_data = valid_ds, epochs = 100, callbacks = [callback, modelcheck2])


triplet_model_result.evaluate(test_ds)

triplet_model_result.save('/home/gangmin_data/capstone_data/my_model')

Epoch 1/100
51/51 [==============================] - 32s 569ms/step - loss: 0.9429 - accuracy: 0.8477 - val_loss: 0.6637 - val_accuracy: 0.8719
INFO:tensorflow:Assets written to: /home/gangmin_data/capstone_data/checkpoint2/assets
Epoch 2/100
51/51 [==============================] - 29s 563ms/step - loss: 0.4951 - accuracy: 0.9580 - val_loss: 0.4080 - val_accuracy: 0.9138
INFO:tensorflow:Assets written to: /home/gangmin_data/capstone_data/checkpoint2/assets
Epoch 3/100
51/51 [==============================] - 29s 554ms/step - loss: 0.2691 - accuracy: 0.9609 - val_loss: 0.3350 - val_accuracy: 0.9163
INFO:tensorflow:Assets written to: /home/gangmin_data/capstone_data/checkpoint2/assets
Epoch 4/100
51/51 [==============================] - 29s 563ms/step - loss: 0.1755 - accuracy: 0.9671 - val_loss: 0.3099 - val_accuracy: 0.9113
INFO:tensorflow:Assets written to: /home/gangmin_data/capstone_data/checkpoint2/assets
Epoch 5/100
51/51 [==============================] - 29s 562ms/step - loss: 

In [148]:
triplet_model_result =tf.keras.models.load_model(checkpoint_path2)
triplet_model_result.evaluate(test_ds)

19/19 [==============================] - 3s 89ms/step - loss: 0.2435 - accuracy: 0.9239


[0.24345999956130981, 0.9238754510879517]

In [56]:
fine_inception.trainable = False

In [57]:
model = tf.keras.Sequential([
    fine_inception,
    tf.keras.layers.GlobalAveragePooling2D(),
    tf.keras.layers.Dense(3),
])

In [58]:
model.compile(loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits= True),
             optimizer = tf.keras.optimizers.Adam(learning_rate= 0.0001),
             metrics = ['accuracy'])


In [59]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
mobilenet_1.00_160 (Function (None, 5, 5, 1024)        3228864   
_________________________________________________________________
global_average_pooling2d_3 ( (None, 1024)              0         
_________________________________________________________________
dense_9 (Dense)              (None, 3)                 3075      
Total params: 3,231,939
Trainable params: 3,075
Non-trainable params: 3,228,864
_________________________________________________________________


In [60]:
callback = tf.keras.callbacks.EarlyStopping(monitor= 'val_loss', patience= 3)
model.fit(train_ds, validation_data= valid_ds, epochs = 100, callbacks= [callback])


Epoch 1/100
49/49 [==============================] - 7s 122ms/step - loss: 1.4159 - accuracy: 0.3471 - val_loss: 1.0341 - val_accuracy: 0.5652
Epoch 2/100
49/49 [==============================] - 6s 112ms/step - loss: 0.9427 - accuracy: 0.5889 - val_loss: 0.8292 - val_accuracy: 0.7187
Epoch 3/100
49/49 [==============================] - 6s 112ms/step - loss: 0.7303 - accuracy: 0.7004 - val_loss: 0.7106 - val_accuracy: 0.7698
Epoch 4/100
49/49 [==============================] - 6s 114ms/step - loss: 0.6696 - accuracy: 0.7343 - val_loss: 0.6449 - val_accuracy: 0.7775
Epoch 5/100
49/49 [==============================] - 6s 111ms/step - loss: 0.5695 - accuracy: 0.7792 - val_loss: 0.6023 - val_accuracy: 0.7903
Epoch 6/100
49/49 [==============================] - 6s 109ms/step - loss: 0.5380 - accuracy: 0.7765 - val_loss: 0.5659 - val_accuracy: 0.7928
Epoch 7/100
49/49 [==============================] - 6s 116ms/step - loss: 0.4857 - accuracy: 0.7915 - val_loss: 0.5435 - val_accuracy: 0.7980

In [61]:
model.evaluate(test_ds)

19/19 [==============================] - 2s 85ms/step - loss: 0.2695 - accuracy: 0.8910


[0.26947149634361267, 0.8910034894943237]

In [62]:
fine_inception.trainable = True

In [63]:
print('number of layers :', len(fine_inception.layers))

number of layers : 86


In [64]:
fine_layer = 60

In [65]:
for layer in fine_inception.layers[:fine_layer]:
    layer.trainable = False

In [66]:
model.compile(loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits= True),
             optimizer = tf.keras.optimizers.Adam(learning_rate= 0.001),
             metrics = ['accuracy'])

In [67]:
model.fit(train_ds, validation_data= valid_ds, epochs = 100, callbacks= [callback])

Epoch 1/100
49/49 [==============================] - 12s 202ms/step - loss: 0.6812 - accuracy: 0.8243 - val_loss: 0.7434 - val_accuracy: 0.8005
Epoch 2/100
49/49 [==============================] - 10s 197ms/step - loss: 0.2389 - accuracy: 0.9194 - val_loss: 0.3481 - val_accuracy: 0.8645
Epoch 3/100
49/49 [==============================] - 10s 200ms/step - loss: 0.1897 - accuracy: 0.9296 - val_loss: 0.4249 - val_accuracy: 0.8593
Epoch 4/100
49/49 [==============================] - 10s 197ms/step - loss: 0.0928 - accuracy: 0.9627 - val_loss: 0.4208 - val_accuracy: 0.9079
Epoch 5/100
49/49 [==============================] - 10s 196ms/step - loss: 0.0474 - accuracy: 0.9829 - val_loss: 0.4668 - val_accuracy: 0.8568


In [68]:
model.evaluate(test_ds)

19/19 [==============================] - 2s 85ms/step - loss: 0.5451 - accuracy: 0.8339


[0.5450819134712219, 0.8339100480079651]