<a href="https://colab.research.google.com/github/kkkkkkkm/capstone/blob/main/torch_logistic_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F 
import torch.optim as optim

In [2]:
torch.manual_seed(1)

In [3]:
x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

In [4]:
print(x_train.shape)
print(y_train.shape)

torch.Size([6, 2])
torch.Size([6, 1])


In [6]:
w = torch.zeros((2,1), requires_grad= True)
b = torch.zeros(1, requires_grad = True)

In [9]:
# 시그모이드 식 구현
h = 1 / (1+torch.exp( -(x_train.matmul(w) +b )))

In [10]:
print(h)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<MulBackward0>)


In [11]:
#torch 제공 시그모이드 
sig_h = torch.sigmoid(x_train.matmul(w) + b)

In [12]:
print(sig_h)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<SigmoidBackward0>)


In [13]:
print(sig_h) #예측값
print(y_train) # 실제값

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<SigmoidBackward0>)
tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.]])


In [15]:
#예측값과 실제값을 이용해 오차율 구하기 cross_entropy 수식 구현
#한 경우에서만

-( (y_train[0]) * torch.log(sig_h[0]) + (1 - y_train[0]) * torch.log(1 - sig_h[0]) )

tensor([0.6931], grad_fn=<NegBackward0>)

In [16]:
#전체의 오차율 구하기
losses = -( (y_train *  torch.log(sig_h)) + ((1-y_train) * torch.log(1-sig_h)) )

In [18]:
print(losses.mean())

tensor(0.6931, grad_fn=<MeanBackward0>)


In [19]:
#라이브러리 제공
F.binary_cross_entropy(sig_h, y_train)

tensor(0.6931, grad_fn=<BinaryCrossEntropyBackward0>)

In [22]:
model = nn.Sequential(
    nn.Linear(2,1),
    nn.Sigmoid()
)

model(x_train)

tensor([[0.3600],
        [0.2872],
        [0.6801],
        [0.4389],
        [0.5216],
        [0.7473]], grad_fn=<SigmoidBackward0>)

In [29]:
#가중치 확인
list(model.parameters())

[Parameter containing:
 tensor([[ 0.3319, -0.6657]], requires_grad=True), Parameter containing:
 tensor([0.4241], requires_grad=True)]

In [51]:
optimizer = optim.SGD( model.parameters(), lr = 0.01)

Epochs = 1000

for epoch in range(Epochs + 1):
  h = model(x_train)

  cost = F.binary_cross_entropy(h, y_train)

 #기울기 초기화
  optimizer.zero_grad()
  
  #현재 가중치로 기울기 계산
  cost.backward()
  
  # 가중치와 바이어스 업데이트
  optimizer.step()

  if epoch % 100== 0:
    predict = h >= torch.FloatTensor([0.5])
    correct_predict = predict.float() == y_train
    accuracy = correct_predict.sum().item() / len(correct_predict)
    print("Epoch : {:4d}/{} , Cost : {:.6f} Accuracy : {:2.2f},".format(epoch, Epochs, cost.item(), accuracy * 100))


Epoch :    0/1000 , Cost : 0.182061 Accuracy : 100.00,
Epoch :  100/1000 , Cost : 0.180413 Accuracy : 100.00,
Epoch :  200/1000 , Cost : 0.178793 Accuracy : 100.00,
Epoch :  300/1000 , Cost : 0.177203 Accuracy : 100.00,
Epoch :  400/1000 , Cost : 0.175639 Accuracy : 100.00,
Epoch :  500/1000 , Cost : 0.174103 Accuracy : 100.00,
Epoch :  600/1000 , Cost : 0.172593 Accuracy : 100.00,
Epoch :  700/1000 , Cost : 0.171109 Accuracy : 100.00,
Epoch :  800/1000 , Cost : 0.169650 Accuracy : 100.00,
Epoch :  900/1000 , Cost : 0.168215 Accuracy : 100.00,
Epoch : 1000/1000 , Cost : 0.166804 Accuracy : 100.00,


In [52]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.3928, 0.2296]], requires_grad=True), Parameter containing:
tensor([-5.0741], requires_grad=True)]
